// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmoxcksznvbomcqpxbhq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1tb3hja3N6bnZib21jcXB4YmhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MDgyNjIsImV4cCI6MjA2OTE4NDI2Mn0.AHKcHP7zIu19rdGe_FUB8KIl64Cy_li94LrYgzCygR8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});